name: Build and Push Custom Perl Images

on: [push, pull_request]

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Log in to github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Perl 5.14 Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: BASE_IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/perl-images:perl-5.014.004-base
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/perl-images:perl-5.014.004
            ghcr.io/ensembl-ci-docker-images/perl-images:perl-5.014.004
#       - name: Build and push Perl 5.30 Image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           build-args: BASE_IMAGE=library/perl:5.30-buster
#           push: true
#           tags: ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/perl-images:perl-5.030.001
